### PR TITLE
Refactor and improve discovery for use with other ONVIF apis

### PR DESCRIPTION
**Pull request by hoxha-saber**
Hello, I am an intern at a company that works with security cameras. We were looking for an API that can help us discover ONVIF cameras on the local network when we came across your code. We liked it. We are currently using it as a service that runs periodically on NVR's.

I made some changes to improve the performance of the class library. Below I will explain the changes and why I think you should include these in your branch.

Firstly, there was a problem sending the WS_PROBE_MESSAGE. On specific computers, we had cameras connected to different NIC cards (network cards) and so the message was not being broadcasted to all possible devices. I changed the UdpClientWrapper so that it will send the message through all NIC's.

Secondly, I changed the way the mac address was being retrieved. The scope string url containing the mac address wasn't always the same. For example, sometimes it was of the form .../mac/14-22-01-23-45 and other times it was .../MAC/14-22-01-23-45. Sometimes it wasn't even there. Instead to retreive mac address, I used the arp command that exists for windows computers. Basically, if you type "arp -a {ip}" in cmd.exe you can get the mac address in a format. I then parsed the string from stdin to get mac.

I also changed the way the manufacturer and model name was retrieved because it wasn't always a consistent regex string.

Finally, I add an if
`if (!String.IsNullOrEmpty (xmlResponse.Body.ProbeMatches[0].Scopes)) { processedResponse.Add (CreateDevice (xmlResponse, response.RemoteEndPoint)); }`
Let me explain what this is doing. WS-Discovery also works for devices other than ONVIF cameras. In fact, it can work with printers. I don't want the program to discover the printer, think it is a camera and insert that into our database. So this if will check to see if the entity found has null probe match. Only devices that are ONVIF compliant have a non null probe match. So the null check removes any devices that are not ONVIF compliant.

Thanks for your time, I hope you consider the changes. Feel free to message me whenever.

### CODE REVIEW

**Comment by vicmaeg** [comment]
Hello @hoxha-saber,

I'm glad this library was helpful to discover ONVIF cameras :).
This library was started as a solution to discover and manage onvif cameras targeting .net standard 2.0, to be able to use it for all frameworks that support .net standard 2.0 (.Net framework, .net core, xamarin, etc.), but I do not have time to continue working on it, that's why the test project is empty :). I had only time to implement the discovery. The client management part should be easy, but did not have time to do it.

When I have time I will review and merge your changes.

Thanks for your time and contribution.

**Comment by vicmaeg** [comment]
Hello @hoxha-saber,

I have created another pull request that you can follow here. https://github.com/vmartos/OnvifSharp/pull/3
I like the changes of using the different nic's, the check on scopes to know if it is an onvif compliant device and the different changes in regex. But I will take a look into the MAC discovery, since i want it to be cross-platform, not windows only.

**Comment by hoxha-saber** [comment]
Yes that seems very fair. Unfortunately, I do not have any onvif cameras with me right now to test as my internship has ended. I do remember that some cameras didn't give the mac address in their probe match result. I think the best way would be to ask the camera directly for its mac address based on the ip.

**Comment by vicmaeg** [comment]
Yes, I will go for that, I will research for a cross-platform tool, or detect the OS and use other tools to get the mac from an IP. I see that arp works for linux also, so it might work :)

**Pull request merged**
