### PR TITLE
Added callback-based device discovery

### LINKED ISSUE #12: Return devices as they reply
Hi,
We're considering using your library in our project.

We have a UI where we want to show the discovered devices, and users would expect devices to appear quite immediately, while the scan can last 30seconds.

Unfortunately, this is not possible with the current API because of this line: 

https://github.com/vmartos/onvif-discovery/blob/c231b1df95039761d3f6ea09ff8ef3fe32864412/OnvifDiscovery/Discovery.cs#L50

A new API entry point could be created with this signature:

```cs
public async Task Discover(Action<DiscoveryDevice> onDeviceDiscovered, int timeout, CancellationToken cancellationToken = default)
```

Thanks to the `onDeviceDiscovered` callback, items could be made available as they reply.
To avoid code duplication, the current entry point could be a wrapper around this new method, like so:

```cs
public async Task<IEnumerable<DiscoveryDevice>> Discover (int timeout, CancellationToken cancellationToken = default)
{
	var devices = new List<DiscoveryDevice> ();
	await this.Discover(devices.Add, timeout, cancellationToken);
	return devices;
}
```

What do you think?
We can make the PR if you want.

### PR DESCRIPTION
**Pull request by jeremyVignelles**
Fixes #12

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
What should I do with the failing test `Discover_CancelBeforeFinish_ReturnsEmptyList` ?

I could just put a

```cs
if(cancellationToken.IsCancellationRequested)
{
   return Array.Empty<DiscoveryDevice>();
}
```

But it doesn't feel right for me : it would mean that nobody replied.
Either you throw an exception with `cancellationToken.ThrowIfCancellationRequested`, or you return the devices you have so far, but I don't see the point of this test.
Moreover, the caller could do that themselves.

**Comment by vicmaeg** [comment]
Hi @jeremyVignelles, thanks for your PR!

Yep, The initial idea is that as the user cancelled the discovery is no more interested in the cameras discovered. But I see the point here that it has no sense.

Maybe you could modify the test that fails with:

`discoveredDevices.Should ().BeEmpty ();`
to
`discoveredDevices.Should ().HaveCount(1)`

I have in mind to improve and add more tests.

The Code changes are OK for me so when you modify the test case I will merge that into master.

Thank you so much!

**Comment by jeremyVignelles** [comment]
I changed the way this test works a bit. It returns a new camera (with an incrementing IP address) every 500 ms, and the Cancellation token is cancelled after 600ms (instead of just after the first reply).

Please tell me if that's OK for you :)

**Comment by jeremyVignelles** [comment]
I can't view the logs so I don't know why the Azure pipeline failed, but since the GitHub one succeeded, I guess it's okay? 🤷

**Comment by vicmaeg** [comment]
I re-run the failed azure pipeline and worked, but the sonarcloud quality gate failed, but I need to investigate why it failed to analyze code coverage. But I will do that later. I will merge that PR. Thanks!

**Comment by jeremyVignelles** [comment]
Great ! Will you publish a nuget package anytime soon ?

**Comment by vicmaeg** [comment]
Yes, probably this weekend!

**Pull request merged**
